function [ new_descriptors_table,...
           new_keypoints_table,...
           new_actives ] = update_table( current_descriptors,... 
                                         descriptors_table,...
                                         current_keypoints,...
                                         keypoints_table,...
                                         actives)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

    indexPairs = matchFeatures(current_descriptors,descriptors_table,'Method',...
             'NearestNeighborSymmetric') ;
    new_actives = zeros(length(actives),1);     
    new_actives(indexPairs(:,1)) = 1;     
    
    
    
         
end

